//! # D-Bus interface proxy for: `com.steampowered.CecDaemon1.CecDevice1`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `com.steampowered.CecDaemon1.CecDevice1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.CecDaemon1.CecDevice1",
    default_service = "com.steampowered.CecDaemon1",
    assume_defaults = true
)]
pub trait CecDevice1 {
    /// GetAudioStatus method
    fn get_audio_status(&self, target: u8) -> zbus::Result<(u8, bool)>;

    /// Mute method
    fn mute(&self, target: u8) -> zbus::Result<()>;

    /// PressOnceUserControl method
    fn press_once_user_control(&self, button: &[u8], target: u8) -> zbus::Result<()>;

    /// PressUserControl method
    fn press_user_control(&self, button: &[u8], target: u8) -> zbus::Result<()>;

    /// ReleaseUserControl method
    fn release_user_control(&self, target: u8) -> zbus::Result<()>;

    /// SendRawMessage method
    fn send_raw_message(&self, raw_message: &[u8], target: u8) -> zbus::Result<u32>;

    /// SendReceiveRawMessage method
    fn send_receive_raw_message(
        &self,
        raw_message: &[u8],
        target: u8,
        opcode: u8,
        timeout: u16,
    ) -> zbus::Result<Vec<u8>>;

    /// SetActiveSource method
    fn set_active_source(&self, phys_addr: i32) -> zbus::Result<()>;

    /// SetOsdName method
    fn set_osd_name(&self, name: &str) -> zbus::Result<()>;

    /// Standby method
    fn standby(&self, target: u8) -> zbus::Result<()>;

    /// VolumeDown method
    fn volume_down(&self, target: u8) -> zbus::Result<()>;

    /// VolumeUp method
    fn volume_up(&self, target: u8) -> zbus::Result<()>;

    /// Wake method
    fn wake(&self) -> zbus::Result<()>;

    /// ReceivedMessage signal
    #[zbus(signal)]
    fn received_message(
        &self,
        initiator: u8,
        destination: u8,
        timestamp: u64,
        message: Vec<u8>,
    ) -> zbus::Result<()>;

    /// UserControlPressed signal
    #[zbus(signal)]
    fn user_control_pressed(&self, button: Vec<u8>, initiator: u8) -> zbus::Result<()>;

    /// UserControlReleased signal
    #[zbus(signal)]
    fn user_control_released(&self, initiator: u8) -> zbus::Result<()>;

    /// LogicalAddresses property
    #[zbus(property)]
    fn logical_addresses(&self) -> zbus::Result<Vec<u8>>;

    /// PhysicalAddress property
    #[zbus(property)]
    fn physical_address(&self) -> zbus::Result<u16>;

    /// VendorId property
    #[zbus(property)]
    fn vendor_id(&self) -> zbus::Result<i32>;
}
