//! # D-Bus interface proxy for: `com.steampowered.CecDaemon1.Config1`
//!
//! This code was generated by `zbus-xmlgen` `5.1.0` from D-Bus introspection data.
//! Source: `Interface '/com/steampowered/CecDaemon1/Daemon' from service 'com.steampowered.CecDaemon1' on system bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::PeerProxy`]
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.CecDaemon1.Config1",
    default_service = "com.steampowered.CecDaemon1",
    default_path = "/com/steampowered/CecDaemon1/Daemon"
)]
pub trait Config1 {
    /// Reload method
    fn reload(&self) -> zbus::Result<()>;

    /// AllowStandby property
    #[zbus(property)]
    fn allow_standby(&self) -> zbus::Result<bool>;

    /// Uinput property
    #[zbus(property)]
    fn uinput(&self) -> zbus::Result<bool>;

    /// LogicalAddress property
    #[zbus(property)]
    fn logical_address(&self) -> zbus::Result<u8>;

    /// Mappings property
    #[zbus(property)]
    fn mappings(&self) -> zbus::Result<Vec<(Vec<u8>, u16)>>;

    /// OsdName property
    #[zbus(property)]
    fn osd_name(&self) -> zbus::Result<String>;

    /// SuspendTv property
    #[zbus(property)]
    fn suspend_tv(&self) -> zbus::Result<bool>;

    /// VendorId property
    #[zbus(property)]
    fn vendor_id(&self) -> zbus::Result<i32>;

    /// WakeTv property
    #[zbus(property)]
    fn wake_tv(&self) -> zbus::Result<bool>;
}
