//! # D-Bus interface proxy for: `com.steampowered.CecDaemon1.Daemon1`
//!
//! This code was generated by `zbus-xmlgen` `5.2.0` from D-Bus introspection data.
//! Source: `com.steampowered.CecDaemon1.Daemon1.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//!
//! [Writing a client proxy]: https://z-galaxy.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "com.steampowered.CecDaemon1.Daemon1",
    default_service = "com.steampowered.CecDaemon1",
    default_path = "/com/steampowered/CecDaemon1/Daemon"
)]
pub trait Daemon1 {
    /// RegisterMessageHandler method
    fn register_message_handler(
        &self,
        opcode: u8,
        path: &zbus::zvariant::ObjectPath<'_>,
        ok: bool,
    ) -> zbus::Result<()>;

    /// Standby method
    fn standby(&self, force: bool) -> zbus::Result<()>;

    /// UnregisterMessageHandler method
    fn unregister_message_handler(&self, opcode: u8, ok: bool) -> zbus::Result<()>;

    /// Wake method
    fn wake(&self) -> zbus::Result<()>;

    /// HandledMessages property
    #[zbus(property)]
    fn handled_messages(&self) -> zbus::Result<Vec<u8>>;
}
